"""empty message

Revision ID: 7edf92997ec1
Revises: 455c84587ff6
Create Date: 2026-04-20 02:01:22.186025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edf92997ec1'
down_revision = '455c84587ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tags', schema=None) as batch_op:
        batch_op.alter_column('user_image_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tags', schema=None) as batch_op:
        batch_op.alter_column('user_image_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
